### ISSUE TITLE
Filter on array mapping

### ISSUE THREAD

**Issue by lixingwang** [project-flogo/core#106]
**Current behavior:**
Today we doing Array mapping with 
`@foreach(SourceArray, loopName)`
**Expected behavior:**
It is very useful to support array mapping base on the filter. `@foreach(SourceArray, loopName, filter)`
For example loop array when only met the certain condition

`@formeach($.result.books, "bookLoop", "$loop.author == 'James'")`

1. `$.result.books`=> source array
2. `bookLoop` => Loop name
3. `$loop.author == 'James'` => filter, iterate the book only when book author equals `James`

**What is the motivation / use case for changing the behavior?**

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by lixingwang** [comment]
@mellistibco @fm-tibco Any thoughts?

**Comment by fm-tibco** [comment]
`@foreach($.result.books, "bookLoop", "$loop.author == 'James'")`

wouldn't it be $loop?

**Comment by lixingwang** [comment]
@fm-tibco Yes, it is `$loop`.  Just edit the description.

**Comment by vijaynalawade** [comment]
@lixingwang what about matching attribute value inside child array nodes? e.g. @foreach($.result.books, "bookLoop", "$loop.book.tags[*] == 'Comedy'") or @foreach($.result.books, "bookLoop", "$loop.book.publishers[*].name == 'ABC'")

**Comment by lixingwang** [comment]
@vijaynalawade  Good question,  today we are not supporting to get all array child data such as `$loop.book.publishers[*].name` If we want to support it, it would return a list of names.

The filter something like this:
`@foreach($.result.books, bookLoop, string.contains($loop.book.publishers[*].name ,'ABC')`

@fm-tibco @mellistibco thoughts to support this kind of use cases?

**Comment by lixingwang** [comment]
@vijaynalawade  After a brief discussion with @mellistibco  and @fm-tibco  offline, we made a decision that we are not going to support filtering on child array.  We can do filtering on child array itself. 

To support special cases which make more complicated and difficult to support many levels.
