### ISSUE TITLE
flogo core install not working 

### ISSUE THREAD

**Issue by jkoenig72** [project-flogo/core#108]
**Current behavior (how does the issue manifest):**

flogo core install not working 

**Expected behavior:**

Flogo core should install

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**git clone https://github.com/project-flogo/core.git**
Cloning into 'core'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 2179 (delta 25), reused 27 (delta 13), pack-reused 2137
Receiving objects: 100% (2179/2179), 544.27 KiB | 1.44 MiB/s, done.
Resolving deltas: 100% (1384/1384), done.

**cd core/
go install ./...** 

go: finding github.com/xeipuuv/gojsonreference latest
go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
go: extracting github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
go: finding github.com/xeipuuv/gojsonpointer latest
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
go: extracting github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
github.com/project-flogo/core/examples/engine/shim
runtime.main_main·f: function main is undeclared in the main package

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

ubuntu 18.04.2

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

flogo --version
flogo cli version v0.9.0

**Additional information you deem important (e.g. issue happens only occasionally):**

none

**Comment by skothari-tibco** [comment]
Flogo core is a repo meant to be used while compilation or execution of Flogo App. Flogo Core is not an application and hence not meant to be installed.
