### ISSUE TITLE
Enhancements for function descriptors

### ISSUE THREAD

**Issue by sayinala** [project-flogo/core#114]
**Current behavior:**
1. The current structure doesn't have support to mention the valueType for argument or return type if they are complex types like an array or object

2. There is no attribute to add an example

3. There is no way to mention the required vs optional arguments

4. There is no way to provide the default value for an argument

**Expected behavior:**
To support the valueType if the type is complex like array or object and added example at the root level
```
{
            "name": "create",
            "description": "Create an array of *primitive types* from the given items. All items must be same primitive types e.g. string, integer etc and must match with the field type where this function is used.",
            "example": "array.create(\"A\",\"B\",\"C\")\nReturns\n[\"A\",\"B\",\"C\"]",
            "varArgs": true,
            "args": [
                {
                    "name": "item1",
                    "type": "any"
                },
                {
                    "name": "item2",
                    "type": "any"
                }
            ],
            "return": {
                "type": "array",
                "valueType": "any"
            }
 }
```
Adding required attribute to args to support required vs optional
```
"args": [
                {
                    "name": "input",
                    "required": false,
                    "type": "array",
                    "valueType": "any"
                }
 ]
```
Adding value under the arg to support default value
```
"args": [
                {
                    "name": "input",
                    "type": "any"
                },
                {
                    "name": "precision",
                    "type": "number",
                    "required": false,
                    "value": 16
                }
]
```

**What is the motivation / use case for changing the behavior?**

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by lixingwang** [comment]
This has been fixed at contrib repo PR https://github.com/project-flogo/contrib/pull/62
