### ISSUE TITLE
Support for special OnStartup/OnShutdown triggers to let app developers initialize/cleanup data using actions

### ISSUE THREAD

**Issue by vijaynalawade** [project-flogo/core#131]
**Current behavior:**
Today, there is no way to configure action that would execute before regular triggers start or after regular triggers are stopped.
**Expected behavior:**
Way to execute action(s) before regular trigger starts and after regular triggers are gracefully stopped.
**What is the motivation / use case for changing the behavior?**
In some cases, users might want to initialize or cleanup things before triggers are started or after triggers are stopped respectively. e.g. create tables in database
**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by lixingwang** [comment]
Fixed at https://github.com/project-flogo/core/pull/215
