### ISSUE TITLE
Problem with Installation

### ISSUE THREAD

**Issue by n-is** [project-flogo/core#143]
When I run:
`go get github.com/project-flogo/core/...`

I get the following:
```
# github.com/project-flogo/core/api
...go\src\github.com\project-flogo\core\api\support.go:236:24: cannot use ac (type *activityContext) as type activity.Context in argument to act.Eval:
        *activityContext does not implement activity.Context (missing GetTracingContext method)
...go\src\github.com\project-flogo\core\support\test\trigger.go:33:21: not enough arguments in call to tConfig.FixUp
        have (*trigger.Metadata)
        want (*trigger.Metadata, resolve.CompositeResolver)
# github.com/project-flogo/core/examples/engine/shim
runtime.main_main·f: function main is undeclared in the main package
```
I am running 64-bit windows home.

**Comment by skothari-tibco** [comment]
The PR #142 should fix it. Thanks

**Comment by n-is** [comment]
There are multiple errors during installation of `project-flogo/contrib` due to this error: `(missing GetTracingContext method)`. I removed the method from `Context` interface as a temporary fix. And it's working well, except the `No tracing configuration found. registering noop-tracer` warning at the start of flogo app.

Thanks for the reply.

**Comment by skothari-tibco** [comment]
I have updated the repo , and it addresses `(missing GetTracingContext method)` error.  So the tests should work fine. Thanks
