### ISSUE TITLE
Supporting index in array mapper

### ISSUE THREAD

**Issue by lixingwang** [project-flogo/core#230]
**Current behavior:**

Today's array mapper does not have a way to let users use the looping index. 

**Expected behavior:**

We should expose the loop index to the user which gives the ability to the user to know the current index of the loop. 

**What is the motivation / use case for changing the behavior?**

Today there is no way to map a primitive array to an object array. 

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by lixingwang** [comment]
@mellistibco @vijaynalawade In order to support this we need a `keyword` to access the loop index.  How about below
1. `$loop.index`
2. `$loop.idx`

Any thoughts?

**Comment by vijaynalawade** [comment]
I prefer $loop.index

**Comment by lixingwang** [comment]
@vijaynalawade @mellistibco To be more clear. We need this keyword more unique because today we also using `$loop.xxxx` to access the array element. To avoid conflict with the array element we should take an as unique as possible
