### ISSUE TITLE
Log total time taken by the handler

### ISSUE THREAD

**Issue by vnalawad-tibco** [project-flogo/core#252]
**Current behavior:**
Today, there is no way to find the total time taken by a handler to process the event.  This is useful metrics to identify performance bottlenecks.
**Expected behavior:**
After completion of the event processing, total time taken by the handler must be printed in logs.
**What is the motivation / use case for changing the behavior?**
Help debug performance issues when SLAs are not met.
**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by lixingwang** [comment]
closed as PR #254 merged
