### ISSUE TITLE
Website flogo.io broken

### ISSUE THREAD

**Issue by juwalter** [project-flogo/core#278]
❗ http://flogo.io/ and https://flogo.io/ are broken

<img width="825" alt="image" src="https://github.com/project-flogo/core/assets/179870/d4b1ee4b-9792-46b3-97d8-71c56b4a5602">

Domain flogo.io ist listed as project homepage by https://github.com/project-flogo/

<img width="638" alt="image" src="https://github.com/project-flogo/core/assets/179870/6bab65e2-744a-401b-85f1-8d31d8cea796">

**Comment by mellistibco** [comment]
fixed.
