### ISSUE TITLE
Is project active

### ISSUE THREAD

**Issue by adlion** [project-flogo/core#282]
Is this project still active?

I mean I was using the old one and the active development is being pushed here, but  I can not find any docs how to start to connect web with flogo

Thank you for the amazing project.
I am a golang developer and can contribute.
Please let me know how  I can contribute.
On the links provided on readme.md there are no open issues.

**Comment by adlion** [comment]
Found it
This tool needs proper documentation

It has a lot of potential.

Thank you.

**Comment by mestadler** [comment]
Same here, I saw some minimal activity several months ago.

**Comment by mellistibco** [comment]
yes, the project is still active. https://github.com/project-flogo has a number of repos related to various different components.
