### ISSUE TITLE
Get trigger status

### ISSUE THREAD

**Issue by lixingwang** [project-flogo/core#67]
**Current behavior:**
This is no way to collect all trigger status
**Expected behavior:**
Should expose engine api to get all trigger status.  just like old: flogoEngine.TriggerInfos()
**What is the motivation / use case for changing the behavior?**

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by mellistibco** [comment]
@lixingwang whats the use case you are thinking of?

**Comment by lixingwang** [comment]
@mellistibco we bundled flogo engines which may have multiple triggers into a container, our infrastructure side continues to check the engine status.   We expose an API which collection all trigger status and response back to infrastructure.

**Comment by lixingwang** [comment]
@mellistibco  we will take it as unhealthy if the trigger status becomes to fail.

**Comment by fm-tibco** [comment]
The ability to get the status is already in the code.  From the engine you can get the App(), and from the app you can get TriggerStatuses()
