### ISSUE TITLE
Future home of flogo-services and distinction between core and flow repos

### ISSUE THREAD

**Issue by matthewcummings** [project-flogo/core#78]
**What is your question?**
I've been looking at https://github.com/TIBCOSoftware/flogo-services and wondering where if it's going to be migrated (or replaced with a new repo) to the project-flogo org. Also, another general question - what are the key differences between this (core) repo and the https://github.com/project-flogo/flow repo?  It's not immediately obvious to me why they're separate.

**Comment by skothari-tibco** [comment]
We look forward to migrate flogo-service in the future. In meantime if you want to monitor `flow` you can go through this https://github.com/TIBCOSoftware/flogo/wiki/Publish-and-Subscribe-Audit-Events . As for the other question `Flow` is a type of action in flogo where as this is a `core` repo which is core Flogo Engine(which provides various APIs for Action, Activity, Trigger, Mapper etc. and also runs the Flogo app). Action is something you perform as a result of trigger. You can execute flow, stream, rules etc.

**Comment by fm-tibco** [comment]
The flogo service have been migrated to https://github.com/project-flogo/services
