### ISSUE TITLE
problem using array mapping in flow input/output mapping 

### ISSUE THREAD

**Issue by lixingwang** [project-flogo/core#79]
**Current behavior (how does the issue manifest):**
Today we use `$.xxx` to get the current scope data, for example, we get the current array loop element by using $.elementName.

We are also using $. to get current scope data for the trigger to flow or flow to trigger mapping. 

There will be an issue when using array mapping in flow input/output mapping, it's difficult to know $.xxx is getting from array scope or trigger scope.
**Expected behavior:**

Need a better way to handle array mapping in trigger output mapping or flow output mapping.

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by fm-tibco** [comment]
Should we come with a way to reference the outer scope within the loop?  $something?  @mellistibco any thoughts?

**Comment by lixingwang** [comment]
@fm-tibco @mellistibco Currently we have `$loop[loopName].xxxx` to get the parent loop(out loop) data.
```
@foreach($.field.addresses, loopName)
```
It's better that we can try to use `$loop` as well.   to get currect loop elements, we can try to use `$loop[.]` or some name which more specific to current loop.

**Comment by fm-tibco** [comment]
We would just do `$loop` for the current loop, and `$loop[name]` to specify a particular loop... the `$loop[.]` looks odd . @mellistibco  thoughts?

**Comment by mellistibco** [comment]
I tend to think that we should make it as simple as possible for accessing the current loop, so just `$loop` seems to make sense. If you're explicitly trying to access an outer loop, it's ok to reference it as you both suggested.

**Comment by lixingwang** [comment]
thanks, @mellistibco and @fm-tibco, I will go with `$loop.xxx` for the current loop.
